name: AWS Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up AWS Credentials using GitHub Secrets
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: 'AKIAUEFYHPDJ7HOQNCNF'
          aws-secret-access-key: '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'
          aws-region: us-east-1

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0 # specify the version of Terraform you want to use

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init


      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Terraform Apply
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' # Apply only on the main branch
        run: terraform apply -auto-approve

